[book]
language = "en"
multilingual = false
src = "."
title = "try-ebiten Documentation"

[output.html]
git-repository-url = "https://github.com/kmdkuk/try-ebiten"
edit-url-template = "https://github.com/kmdkuk/try-ebiten/edit/main/docs/{path}"
site-url = "/try-ebiten/"
